const items = [
    {
        category: 'material_ui',
        img: 'shop/material_ui/cover.png',
        textImg: 'shop/material_ui/text-img.png',
        items: [
            {   
                id: "material_ui",
                category: 'theme',
                img: 'shop/material_ui/img-1.png',
                name: 'Material UI',
                label: 'MAXIMILIAN',
                labelTextColor: '#000',
                labelColor: '#97C5E7',
                isFree: true,
                price: 0,
            },
            {   
                id: "material_ui",
                category: 'colors',
                img: 'shop/material_ui/img-2.png',
                name: 'Material colors',
                label: 'MAXIMILIAN',
                labelTextColor: '#000',
                labelColor: '#97C5E7',
                isFree: true,
                price: 500,
            },
        ]
    },

    {
        category: 'simple_light',
        img: 'shop/simple_light/cover.png',
        textImg: 'shop/simple_light/text-img.png',
        items: [
            {   
                id: "simple_light",
                category: 'theme',
                img: 'shop/simple_light/img-1.png',
                name: 'Светлая простота',
                label: 'Тест',
                labelTextColor: '#000',
                labelColor: '#fff',
                isFree: true,
                price: 0,
            },
            {   
                id: "simple_light",
                category: 'colors',
                img: 'shop/simple_light/img-2.png',
                name: 'Светлые краски',
                label: 'Тест',
                labelTextColor: '#000',
                labelColor: '#fff',
                isFree: true,
                price: 0,
            },
            {   
                id: "simple_light",
                category: 'emojies',
                img: 'shop/simple_light/img-3.png',
                name: 'Просто эмодзи',
                label: 'Тест',
                labelTextColor: '#000',
                labelColor: '#fff',
                isFree: true,
                price: 0,
            },
            {   
                id: "simple_light",
                category: 'all',
                img: 'shop/simple_light/img-4.png',
                name: 'Просто набор',
                label: 'Тест',
                labelTextColor: '#000',
                labelColor: '#fff',
                isFree: true,
                price: 0,
            },
        ]
    }, 

    {
        category: 'winter_2024',
        img: 'shop/winter_2024/cover.png',
        textImg: 'shop/winter_2024/text-img.png',
        items: [
            {   
                id: "winter_2024",
                category: 'theme',
                img: 'shop/winter_2024/img-1.png',
                name: 'Морозная свежесть',
                label: 'Зима 2024',
                labelTextColor: '#fff',
                labelColor: '#85AFED',
                isFree: true,
                price: 0,
            },
            {   
                id: "winter_2024",
                category: 'colors',
                img: 'shop/winter_2024/img-2.png',
                name: 'Морозная палитра',
                label: 'Зима 2024',
                labelTextColor: '#fff',
                labelColor: '#85AFED',
                isFree: true,
                price: 0,
            },
            {   
                id: "winter_2024",
                category: 'emojies',
                img: 'shop/winter_2024/img-3.png',
                name: 'Морозные эмодзи',
                label: 'Зима 2024',
                labelTextColor: '#fff',
                labelColor: '#85AFED',
                isFree: true,
                price: 0,
            },
            {   
                id: "winter_2024",
                category: 'all',
                img: 'shop/winter_2024/img-4.png',
                name: 'Морозный пак',
                label: 'Зима 2024',
                labelTextColor: '#fff',
                labelColor: '#85AFED',
                isFree: true,
                price: 0,
            },
        ]
    }, 
    
    {
        category: 'kyrgyzstan',
        img: 'shop/kyrgyzstan/cover.png',
        textImg: 'shop/kyrgyzstan/text-img.png',
        items: [
            {   
                id: "kyrgyzstan",
                category: 'theme',
                img: 'shop/kyrgyzstan/img-2.png',
                name: 'Тема',
                label: 'День независимости',
                labelTextColor: '#fff',
                labelColor: '#E3010F',
                isFree: true,
                price: 0,
            },
            {   
                id: "kyrgyzstan",
                category: 'emojies',
                img: 'shop/kyrgyzstan/img-1.png',
                name: 'Смайлы',
                label: 'День независимости',
                labelTextColor: '#fff',
                labelColor: '#E3010F',
                isFree: true,
                price: 0,
            },
            {   
                id: "kyrgyzstan",
                category: 'colors',
                img: 'shop/kyrgyzstan/img-3.png',
                name: 'Пак цветов',
                label: 'День независимости',
                labelTextColor: '#fff',
                labelColor: '#E3010F',
                isFree: true,
                price: 0,
            },
            {   
                id: "kyrgyzstan",
                category: 'all',
                img: 'shop/kyrgyzstan/img-4.png',
                name: 'Пак "Родина"',
                label: 'День независимости',
                labelTextColor: '#fff',
                labelColor: '#E3010F',
                isFree: true,
                price: 0,
            },
        ]
    },  
    {
        category: 'genery',
        img: 'shop/genery/cover.png',
        textImg: 'shop/genery/text-img.png',
        items: [
            {   
                id: "genery",
                category: 'theme',
                img: 'shop/genery/img-1.png',
                name: 'Тема',
                label: '1 год вместе',
                labelTextColor: '#fff',
                labelColor: 'linear-gradient(90deg, #2400FF 1%, #00C2FF 100%)',
                isFree: true,
                price: 1000,
            },
            {
                id:'genery',
                img: 'shop/genery/img-2.png',
                category: 'colors',
                name: 'Пак смайлов',
                label: '1 год вместе',
                labelTextColor: '#fff',
                labelColor: 'linear-gradient(90deg, #2400FF 1%, #00C2FF 100%)',
                isFree: true,
                price: 250,
            },
            {
                id:'genery',
                img: 'shop/genery/img-3.png',
                category: 'emojies',
                name: 'Пак смайлов',
                label: '1 год вместе',
                labelTextColor: '#fff',
                labelColor: 'linear-gradient(90deg, #2400FF 1%, #00C2FF 100%)',
                isFree: true,
                price: 500,
            },
            {
                id:'genery',
                img: 'shop/genery/img-4.png',
                category: 'all',
                name: 'Набор Genery',
                label: '1 год вместе',
                labelTextColor: '#fff',
                labelColor: 'linear-gradient(90deg, #2400FF 1%, #00C2FF 100%)',
                isFree: true,
                price: 0,
            },
        ]
    },
];


export default items;
