// themes.js
const themes = {
    'default': {
        name: 'default',
        icon_color: '#0040F9',
        first_color: '#0040F9',
        second_color: "#C3F82B",
        third_color: "#FF4365",
        gradient_first_color: '#0040F9',
        gradient_second_color: '#C3F82B',
        block_first_color: '#0040F9',
        block_second_color: '#C3F82B',
        block_third_color: '#FF4365',
        block_border_color: 'none',
        block_arrow_first_color: 'none',
        block_arrow_second_color: 'none',
        block_arrow_third_color: 'none',
        background_color: "#0A0B10",
        shadow_color: '#10232f12',
        loader_first_color: '#444453',
        loader_second_color: '#2D2D37',
        text_first_color: "#FFFFFF",
        text_second_color: "#0A0B10",
        text_third_color: "#FFFFFF",
        arrow_background_color: "#131318",
        element_first_color: "#1C1C23",
        element_second_color: "#3A3A47",
        active_element_color: '#1D1D22',
        casino_first_color: "#007350",
        casino_second_color: "#730015",
        casino_third_color: "#030001",
        casino_wheel_first_color: "#1C1C23",
        casino_wheel_second_color: "#25252F",
    },
    'genery': {    
        name: 'genery',
        icon_color: 'linear-gradient(70deg, #2400FF 0%, #00C2FF 100%)',
        first_color: 'linear-gradient(70deg, #2400FF 0%, #00C2FF 100%)',
        second_color: "linear-gradient(70deg, #C3F82B 0%, #00FF66 100%)",
        third_color: "linear-gradient(70deg, #FF4365 0%, #AD00FF 100%)",
        gradient_first_color: '#2400FF',
        gradient_second_color: '#00C2FF',
        block_first_color: 'linear-gradient(70deg, #2400FF 0%, #00C2FF 100%)',
        block_second_color: 'linear-gradient(70deg, #C3F82B 0%, #00FF66 100%)',
        block_third_color: 'linear-gradient(70deg, #FF4365 0%, #AD00FF 100%)',
        block_border_color: 'none',
        block_arrow_first_color: 'none',
        block_arrow_second_color: 'none',
        block_arrow_third_color: 'none',
        background_color: "#0A0B10",
        shadow_color: '#10232f12',
        loader_first_color: '#444453',
        loader_second_color: '#2D2D37',
        text_first_color: "#FFFFFF",
        text_second_color: "#0A0B10",
        text_third_color: "#FFFFFF",
        arrow_background_color: "#131318",
        element_first_color: "#1C1C23",
        element_second_color: "#3A3A47",
        active_element_color: '#1D1D22',
        casino_first_color: "#007350",
        casino_second_color: "#730015",
        casino_third_color: "#030001",
        casino_wheel_first_color: "#1C1C23",
        casino_wheel_second_color: "#25252F",
    },
    // добавьте больше тем по мере необходимости
  }
  
export default themes
  